# -*- coding: utf-8 -*-
# Deployment settings for Stage1.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.4/s3e/makefile_builder/mkb.py', 'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/Stage1.mkb', '--buildenv=VC10X', '--debug', '--x86', '--no-ide', '--execute', '--deploy-only']
mkb = 'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/Stage1.mkb'
mkf = ['c:\\marmalade\\7.4\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.4\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.4\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.4\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.4\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.4\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.4\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.4\\extensions\\pvrtextool\\pvrtextool.mkf', 'c:\\marmalade\\7.4\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.4\\examples\\marmaladeexampleresources\\marmaladeexampleresources.mkf', 'c:\\marmalade\\7.4\\examples\\gametutorial\\cpp\\stage1\\libs\\cjson-for-marmalade\\cjson.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/data/textures', 'textures', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'Stage1'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'Stage1'
    long_caption = 'Stage1'
    version = [0, 0, 1]
    config = ['c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/data/app.icf']
    data_dir = 'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/data'
    mkb_dir = 'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1'
    iphone_link_lib = []
    osx_ext_dll = ['c:/marmalade/7.4/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.4/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    splashscreen = 'c:/marmalade/7.4/examples/marmaladeexampleresources/resources/splashscreens'
    blackberry_extra_descriptor = []
    ws8_extra_res = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    icon = 'c:/marmalade/7.4/examples/marmaladeexampleresources/resources/icons'
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_gcc_x86/Stage1.so',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_gcc_x86/Stage1.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_gcc_x86_tizen/Stage1.s86',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_gcc_x86_tizen/Stage1.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_firefoxos/Stage1.js',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_firefoxos/Stage1.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_gcc_mips/Stage1.so',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_gcc_mips/Stage1.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_gcc_arm/Stage1.s3e',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_gcc_arm/Stage1.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_gcc_mips/Stage1.so',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_gcc_mips/Stage1.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_gcc_x86_android/Stage1.so',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_gcc_x86_android/Stage1.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_arm/Stage1.s3e',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_arm/Stage1.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Debug_Stage1_VC10X_x86/Stage1.s86',
                   'release' : r'c:/Marmalade/7.4/examples/GameTutorial/CPP/Stage1/build_stage1_vc10x/Release_Stage1_VC10X_x86/Stage1.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
